package cmd

import (
	"fmt"

	"github.com/spacemeshos/spacecraft/log"
	"github.com/spacemeshos/spacecraft/network"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var createNetworkCmd = &cobra.Command{
	Use:   "createNetwork",
	Short: "Create a network",
	Long: `Create a new network with N miners and N PoETs. For example:
	
spacecraft createNetwork -m=10 -p=3

Or else create a network that joins another network using a config file generated by parent network. For example:

spacecraft createNetwork -m=10 -p=3 --network-name=devnet1 --bootstrap=false --miner-go-sm-config=./config.json
`,
	Run: func(cmd *cobra.Command, args []string) {
		err := network.Create()
		if err != nil {
			log.Error.Println(err)
			return
		}

		log.Success.Println("network created successfully")
	},
}

func init() {
	rootCmd.AddCommand(createNetworkCmd)

	createNetworkCmd.Flags().StringVar(&config.GoSmConfig, "go-sm-config", config.GoSmConfig, "config file for go-spacemesh")
	createNetworkCmd.Flags().StringVar(&config.KibanaSavedObjects, "kibana-saved-objects", config.KibanaSavedObjects, "path of file exported using kibana export API")
	createNetworkCmd.Flags().IntVarP(&config.NumberOfMiners, "miners", "m", config.NumberOfMiners, "number of miners")
	createNetworkCmd.Flags().IntVarP(&config.NumberOfPoets, "poets", "p", config.NumberOfPoets, "number of poets")
	createNetworkCmd.Flags().StringVar(&config.MinerMemory, "miner-ram", config.MinerMemory, "RAM for each miner")
	createNetworkCmd.Flags().StringVar(&config.MinerCPU, "miner-cpu", config.MinerCPU, "vCPUs for each miner")
	createNetworkCmd.Flags().StringVar(&config.PoetMemory, "poet-ram", config.PoetMemory, "RAM for each poet")
	createNetworkCmd.Flags().StringVar(&config.PoetCPU, "poet-cpu", config.PoetCPU, "vCPUs for each poet")
	createNetworkCmd.Flags().StringVar(&config.MinerDiskSize, "miner-disk-size", config.MinerDiskSize, "Disk size of miner in GB")
	createNetworkCmd.Flags().StringVar(&config.PoetDiskSize, "poet-disk-size", config.PoetDiskSize, "Disk size of poet in GB")
	createNetworkCmd.Flags().StringVar(&config.GoSmImage, "go-sm-image", config.GoSmImage, "docker image for go-spacemesh build")
	createNetworkCmd.Flags().StringVar(&config.PoetImage, "poet-image", config.PoetImage, "docker image for poet build")
	createNetworkCmd.Flags().IntVar(&config.PoetGatewayAmount, "poet-gateway-amount", config.PoetGatewayAmount, "number of gateway to pass when activating poet(s)")
	createNetworkCmd.Flags().IntVar(&config.BootnodeAmount, "bootnode-amount", config.BootnodeAmount, "total bootnodes in the generated config file")
	createNetworkCmd.Flags().IntVar(&config.GCPMachineCPU, "gcp-machine-cpu", config.GCPMachineCPU, "total CPU the GCP machine type has")
	createNetworkCmd.Flags().IntVar(&config.GCPMachineMemory, "gcp-machine-memory", config.GCPMachineMemory, "total memory the GCP machine type has")
	createNetworkCmd.Flags().IntVar(&config.GenesisDelay, "genesis-delay", config.GenesisDelay, "delay in minutes after network startup for genesis")
	createNetworkCmd.Flags().BoolVar(&config.Bootstrap, "bootstrap", config.Bootstrap, "bootstrap a new network without connecting to an existing network")
	createNetworkCmd.Flags().StringVar(&config.MinerGoSmConfig, "miner-go-sm-config", config.MinerGoSmConfig, "config file location for the miners (example \"./config.json\")")
	createNetworkCmd.Flags().StringVar(&config.ESDiskSize, "es-disk-size", config.ESDiskSize, "disk size to allocate to elasticsearch")
	createNetworkCmd.Flags().StringVar(&config.ESCPU, "es-cpu", config.ESCPU, "vCPUs to allocate to elasticsearch")
	createNetworkCmd.Flags().StringVar(&config.ESMemory, "es-memory", config.ESMemory, "RAM to allocate to elasticsearch")
	createNetworkCmd.Flags().StringVar(&config.LogstashDiskSize, "logstash-disk-size", config.LogstashDiskSize, "disk size to allocate to logstash")
	createNetworkCmd.Flags().StringVar(&config.LogstashCPU, "logstash-cpu", config.LogstashCPU, "vCPUs to allocate to logstash")
	createNetworkCmd.Flags().StringVar(&config.LogstashMemory, "logstash-memory", config.LogstashMemory, "RAM to allocate to logstash")
	createNetworkCmd.Flags().StringVar(&config.KibanaCPU, "kibana-cpu", config.KibanaCPU, "vCPUs to allocate to kibana")
	createNetworkCmd.Flags().StringVar(&config.KibanaMemory, "kibana-memory", config.KibanaMemory, "RAM to allocate to kibana")
	createNetworkCmd.Flags().StringVar(&config.LogsExpiry, "logs-expiry", config.LogsExpiry, "number of days after which logs are deleted automatically")

	err := viper.BindPFlags(createNetworkCmd.Flags())
	if err != nil {
		fmt.Println("an error has occurred while binding flags:", err)
	}
}